# CREATE DATABASE LOCADORA_DE_VEICULOS;

CREATE TABLE IF NOT EXISTS VEICULOS ( 
	COD_VEICULO INT PRIMARY KEY AUTO_INCREMENT,
	MODELO VARCHAR(100) NOT NULL,
    MARCA VARCHAR(100) NOT NULL,
    ANO INT NOT NULL,
    STATUS_VEICULO VARCHAR(20) NOT NULL,
    PRECO_DIARIA DECIMAL(10, 2) NOT NULL
); 

CREATE TABLE IF NOT EXISTS CLIENTES ( 
	COD_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME_CLIENTE VARCHAR(100) NOT NULL,
    EMAIL_CLIENTE VARCHAR(100) NOT NULL,
    CIDADE VARCHAR(50) NOT NULL,
    IDADE INT NOT NULL,
    CATEGORIA_CLIENTE VARCHAR(20) NOT NULL
);

INSERT INTO VEICULOS(COD_VEICULO, MODELO, MARCA, ANO, STATUS_VEICULO, PRECO_DIARIA) 
	VALUES(DEFAULT, "NIVUS", "VOLKSWAGEM", 2011, "PRONTO_PARA_USO", 200.50);

SELECT * FROM VEICULOS_PARA_ATUALIZAR;

-- CRIA UMA TABELA TEMPORARIA COM OS COD_VEICULO A SEREM ATUALIZADOS
CREATE TEMPORARY TABLE VEICULOS_PARA_ATUALIZAR AS 
	SELECT COD_VEICULO FROM VEICULOS WHERE ANO <= 2020; 

UPDATE VEICULOS SET PRECO_DIARIA = PRECO_DIARIA + (PRECO_DIARIA * 0.1) WHERE COD_VEICULO IN (SELECT COD_VEICULO FROM VEICULOS_PARA_ATUALIZAR);

ALTER TABLE CLIENTES ADD COLUMN ANOS_DE_ASSOCIACAO INT NOT NULL;

INSERT INTO CLIENTES(COD_CLIENTE, NOME_CLIENTE, EMAIL_CLIENTE, CIDADE, IDADE, CATEGORIA_CLIENTE, ANOS_DE_ASSOCIACAO)
	VALUES(DEFAULT, "PAULINHO", "paulinhouba@hotmail.com", "UBATUBA", 31, "PRATA", 7);
    
SELECT * FROM CLIENTES;    

CREATE TEMPORARY TABLE CLIENTES_PARA_ATUALIZAR AS
	SELECT COD_CLIENTE FROM CLIENTES WHERE ANOS_DE_ASSOCIACAO > 5 ;

UPDATE CLIENTES SET CATEGORIA_CLIENTE = "OURO" WHERE COD_CLIENTE IN (SELECT COD_CLIENTE FROM CLIENTES_PARA_ATUALIZAR);    
    

